#!/bin/bash
# 
# For the PSB Pipeline, SIFTS has two critical datasets.  Both are pre-loaded
# into SQL tables prior to pipeline runs.
#
# For canonical uniprot IDs, the below downloaded xml alignment files are 
# parsed and loaded into SQL tables by pdbmap/scripts/sifts_parser.py with the --legacy flag.
#
# citation:  Velankar et al., Nucleic Acids Research 41, D483 (2013) 
#
# Non-canonical uniprot transcript to PDB chain alignments are also parsed by sifts_parser.py.
# However, these are loaded not from files downloaded here, but from the REST API document here:
#
# citation:  Dana .. Velankar et al., Nucleic Acids Research 47, D1, D482-489 (2018) 
#            SIFTS: updated Structure Integration with Function, Taxonomy and 
#            Sequences resource allows 40-fold increase in coverage of
#            structure-based annotations for proteins


USER=`whoami`
DATE=`date +%Y-%m-%d`

mkdir -v $DATE

cp ${0##*/} $DATE

# For description of the SIFTS alignment resources, both RestAPI and download XML files, see:
# https://www.ebi.ac.uk/pdbe/docs/sifts/ 

# First download is a large cross-reference file
cmd="wget -q -N --reject -nH -nd --timeout=100000 ftp://ftp.ebi.ac.uk/pub/databases/msd/sifts/flatfiles/tsv/pdb_chain_uniprot.tsv.gz -P $DATE"
echo $cmd
eval $cmd
retval=$?
if [ $retval -ne 0 ]; then 
     echo "FAILURE $retval returned from $cmd"
     exit $retval
fi

# gunzip -c $DATE/pdb_chain_uniprot.tsv.gz > $DATE/pdb_chain_uniprot.tsv
# rm $DATE/pdb_chain_uniprot.tsv.gz

# wget 
cmd="wget --no-directories --recursive --timestamping -N --no-parent --no-host-directories --timeout=100000 --tries=100 -P $DATE/xml ftp://ftp.ebi.ac.uk/pub/databases/msd/sifts/split_xml"

echo $cmd
eval $cmd
retval=$?
if [ $retval -ne 0 ]; then 
    echo "FAILURE $retval returned from $cmd"
    exit $retval
fi

xml_files_count=`echo $DATE/xml/* | wc -w`
echo $xml_files_count " xml files were downloaded"


# Create README
echo "# MAINTAINER: $USER" >> $DATE/README
echo "# EMAIL: chris.moth@vanderbilt.edu" >> $DATE/README
echo "# LAST_UPDATE: $DATE" >> $DATE/README
echo "# update_cmd: ${0}" >> $DATE/README

echo "" >> $DATE/README
echo "MANIFEST:" >> $DATE/README
ls $DATE >> $DATE/README
# fix up the "current" symlink to the current date
rm -f current
ln -s $DATE current
